Upgrade Playwright (#38414)
* Upgrade `playwright-sharp-tool`

https://www.nuget.org/packages/playwright-sharp-tool

Contributes towards https://github.com/dotnet/aspnetcore/issues/30882.

* Update to latest v1.16.1 from GitHub

https://github.com/microsoft/playwright-dotnet/releases/tag/v1.16.1

* Update to use Microsoft.Playwright

* Update references to reflect `Microsoft.Playwright`

* Update dotnet-tools.json

* Upgrade System.CommandLine

* Adapt to breaking API changes in Playwright

* Upgrade dotnet-serve

* Add Microsoft.Playwright.CLI

* Revert "Upgrade System.CommandLine"

This reverts commit cc46e9cfb7a5bd75cb6454aac07fbeb96e6040f7.

* Fix build

The build failed. Fix the build errors and run again.
C:\h\w\AA180980\w\9ED808A4\e\RunTests\RunTests.csproj : warning NU1604: Project dependency Microsoft.Playwright does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
C:\h\w\AA180980\w\9ED808A4\e\RunTests\TestRunner.cs(124,35): error CS7036: There is no argument given that corresponds to the required formal parameter 'arguments' of 'ProcessUtil.RunAsync(string, string, string?, string?, bool, IDictionary<string, string?>?, Action<string>?, Action<string>?, Action<int>?, CancellationToken)' [C:\h\w\AA180980\w\9ED808A4\e\RunTests\RunTests.csproj]

* Remove semaphore for websocket events

* Update playwrightSettings based on breaking changes

* npx based playwright install

* npm install playwright

* Install node in helix env

* Use DOTNET_ROLL_FORWARD with `dotnet` `playwright` tool

* Cleanup

* Update playwright tool usage

* DOTNET_ROLL_FORWARD in TestRunner

* Specify project dir

* Playwright install without cli

* Update TestRunner.cs

* Update TestRunner.cs

* Re-enable helix playwright tests

* Upgrade Playwright to 1.17.3, CLI to 1.2.2

* Fix spacing

* Remove DOTNET_ROLL_FORWARD

* PR Feedback

* Remove temp project workaround.

* Fix package lowerbound issue

* Update Versions.props

* Update BrowserManager.cs

* Remove `Installing Microsoft.Playwright.CLI`

* Disable playwright tests in helix