Update InternalServerError.cs (#55572)
The license header was missing which caused unified-build to fail.

>     D:\a\_work\1\vmr\src\aspnetcore\src\Http\Http.Results\src\InternalServerError.cs(1,1): error IDE0073: A source file is missing a required header. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0073) [D:\a\_work\1\vmr\src\aspnetcore\src\Http\Http.Results\src\Microsoft.AspNetCore.Http.Results.csproj]